const dataJson = {
    types : [
        {cd : 'A01', nm : '적응형'},
        {cd : 'A02', nm : '유지보수'},
        {cd : 'A03', nm : '반응형'},
        {cd : 'A04', nm : '웹접근성'},
        {cd : 'A05', nm : 'php개발'},
        {cd : 'A06', nm : '고도몰'},
        {cd : 'A07', nm : 'mobile'},

    ],
    works : [
        {
            company : "unbiz",
            filterType : ['A01', 'A02'],
            title : 'KPGA 통합플랫폼 운영 및 고도화 용역',
            summary:'kpga는 한국 남자 프로골프의 공식정보를 확인할수 있는 사이트이며, 사용자 홈페이지 및 Admin 페이지 유지보수 작업하였습니다.',
            detail : 'https://www.notion.so/KPGA-1b8e57ca973b80f6b979ee5a7988ef20?pvs=4',
            link : 'https://www.kpga.co.kr/',
            thumbImb:'unbiz_kpga',
        },
        {
            company : "unbiz",
            filterType : ['A02','A03'],
            title : '프로스포츠정보광장',
            summary:'프로스포츠에서 운영하는 사이트이며, 전체적인 페이지 개편을 위해 퍼블리싱 하였고, 모바일 및 pc 디자인을 디자이너와 협의하며 퍼블리싱 작업하였습니다.',
            detail : 'https://www.notion.so/200e57ca973b800dbee1d9c8ef861061?pvs=4',
            link : '',
            thumbImb:'unbiz_porsport',
        },
        {
            company : "unbiz",
            filterType : ['A02','A01'],
            title : '대한복싱협회 홈페이지',
            summary:'대한복싱협회에서 운영하는 홈페이지이며, 홈페이지 개편하며 퍼블리싱을 작업하였습니다.',
            detail : 'https://www.notion.so/200e57ca973b8086a766dd153134a173?pvs=4',
            link : 'http://boxing.sports.or.kr/',
            thumbImb:'unbiz_boxing',
        },
        {
            company : "unbiz",
            filterType : ['A02','A01'],
            title : '대한펜싱협회 홈페이지',
            summary:'대한복싱협회에서 운영하는 홈페이지이며, 홈페이지 개편 하여 퍼블리싱을 작업하였고, 적응형으로 작업하였습니다.',
            detail : 'https://www.notion.so/200e57ca973b8066924af0c8db7024fd?pvs=4',
            link : '',
            thumbImb:'unbiz_fencing',
        },
        {
            company : "unbiz",
            filterType : ['A07'],
            title : '대한펜싱협회 앱',
            summary:'펜싱협회 어플 사용자 화면 유지보수 퍼블리싱 작업하였으며, :before, :after를 사용하여 랭킹 대진표를 작업하였습니다.',
            detail : 'https://www.notion.so/APP-200e57ca973b803699c5e48f4de032ef?pvs=4',
            link : 'https://play.google.com/store/apps/details?id=co.kr.kff.kff&hl=ko&pli=1',
            thumbImb:'unbiz_fencingApp',
        },
        {
            company : "unbiz",
            filterType : ['A02'],
            title : '경상남도체육회 홈페이지 유지보수',
            summary:'경상남도 내 다양한 스포츠 종목별 협회 소개 사이트이며 결과를 제공하는 페이지를 유지보수 하였습니다.',
            detail : 'https://www.notion.so/1c8e57ca973b8045b494d3c25c0eade4?pvs=4',
            link : 'http://www.gnsports.or.kr/index.do',
            thumbImb:'unbiz_gnsports',
        },
        {
            company : "unbiz",
            filterType : ['A01'],
            title : '드웰시티개발',
            summary:'신규 홈페이지 프로젝트이며, 적응형으로 퍼블리싱 작업하였습니다.',
            detail : 'https://www.notion.so/1c8e57ca973b80f59b32dffaf5e171b2?pvs=4',
            link : 'http://www.thewellcity.kr/',
            thumbImb:'unbiz_thewellcity',
        },
        {
            company : "unbiz",
            filterType : ['A02'],
            title : '프로스포츠 암표',
            summary:'한국의 프로스포츠와 관련된 비리, 부정행위, 스포츠 윤리 위반 사항 등을 신고할 수 있는 공식 플랫폼입니다. 한국프로스포츠협회에서 운영하며, 공정하고 투명한 스포츠 환경 조성을 목적으로 합니다.',
            detail : 'https://www.notion.so/1c8e57ca973b8009af79d7363b9bb356?pvs=4',
            link : 'http://report.prosports.or.kr/report',
            thumbImb:'unbiz_porsport_report',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A04'],
            title : '남도사이버갤러리 웹접근성 검사',
            summary:'메인 페이지를 유지보수 퍼블리싱 작업을 하였고, 웹접근성 검사 진단을 하여 웹표준 코딩하였습니다.',
            detail : '',
            link : 'https://namdogallery.or.kr/main/main.html',
            thumbImb:'unipics_namdo',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A04'],
            title : '남도사이버갤러리 php 개발',
            summary:'소장품샵 페이지를 sql을 사용하여 Admin 페이지와 User페이지 연동하였습니다.',
            detail : '',
            link : 'https://namdogallery.or.kr/shop/nd_shoplist.html',
            thumbImb:'unipics_namdo',
        },
        {
            company : "unipics",
            filterType : ['A07'],
            title : '메이커스페이스 앱',
            summary:'출입관리하는 시스템 어플의 사용자 화면을 퍼블리싱 작업하였으며, 하드코딩을 했습니다.',
            detail : 'https://www.notion.so/1b6e57ca973b8063afe0d7990de5b000?pvs=4',
            link : '',
            thumbImb:'unipics_makersApp',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A02'],
            title : 'KEA 한국전자정보통신산업진흥회',
            summary:'유지보수 퍼블리싱 작업을 하였습니다. ',
            detail : 'https://www.notion.so/KEA-1b6e57ca973b80348997e5d6946c53f7?pvs=4',
            link : 'https://www.gokea.org/core/?cid=89',
            thumbImb:'unipics_kea',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A02'],
            title : '한국자동차연구원',
            summary:'KEA에서 연계하는 페이지이며, 유지보수 퍼블리싱 작업을 하였습니다. 또한, 부서소개 페이지, 메인페이지 수정작업을 하였으며, 반응형 작업 하였습니다.',
            detail : 'https://www.notion.so/1b7e57ca973b80daa114efe2f2e46098?pvs=4',
            link : 'https://edu.katech.re.kr',
            thumbImb:'unipics_katech',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A02'],
            title : '차세대 바이오헬스산업 혁신인재양성사업',
            summary:'KEA에서 연계하는 페이지이며, 유지보수 퍼블리싱 작업을 하였습니다. 또한, 사업안내 페이지에 있는 주관대학 소개 페이지 퍼블리싱 작업 하였습니다.',
            detail : 'https://www.notion.so/1b7e57ca973b8060af42d4ea4fd681bf?pvs=4',
            link : 'https://biohealthedu.org/core/?cid=35',
            thumbImb:'unipics_biho',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A02'],
            title : '차세대융합기술연구원 메이커스페이스 전문랩',
            summary:'KEA에서 연계하는 페이지이며, 유지보수 퍼블리싱 작업을 하였습니다.',
            detail : 'https://www.notion.so/1b7e57ca973b80b295d4d02c2c26818b?pvs=4',
            link : 'https://www.aictms.or.kr/core/?cid=65',
            thumbImb:'unipics_makers',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A02'],
            title : '미래형자동차 기술혁신인재양성',
            summary:'KEA에서 연계하는 페이지이며, 유지보수 퍼블리싱 작업을 하였습니다.',
            detail : 'https://www.notion.so/1b8e57ca973b80c8811ecc033fd496b9?pvs=4',
            link : 'https://www.futurecaredu-bc.org/core/?cid=25',
            thumbImb:'unipics_future',
        },
        {
            company : "unipics",
            filterType : ['A03'],
            title : '한국자동차환경협회 전기차충전인프라 교육센터',
            summary:'KEA에서 연계하는 페이지이며, 메인 페이지 및 일부 서브페이지를 퍼블리싱을 메인으로 작업하였습니다.',
            detail : 'https://www.notion.so/1b8e57ca973b801f9866ff4b4e05aaff?pvs=4',
            link : 'https://edu.aea.or.kr/main/',
            thumbImb:'unipics_edu',
        },
        {
            company : "unipics",
            filterType : ['A03'],
            title : '미래형자동차 현장인력양성사업',
            summary:'보조역할로 퍼블리싱 작업하였으며, 서브페이지 유지보수 및 메인 페이지를 작업하였습니다.',
            detail : 'https://www.notion.so/KEA-1b8e57ca973b80d0a405f8a1bb6e7a81?pvs=4',
            link : '',
            thumbImb:'unipics_carStudy',
        },
        {
            company : "unipics",
            filterType : ['A03'],
            title : '한국디지털헬스산업협회',
            summary:'메인으로 퍼블리싱 작업을 하였으며, 오픈소스를 통해 자바스크립트를 사용하여 제작하였습니다.',
            detail : 'https://www.notion.so/1b8e57ca973b80f39feef15ed2516379?pvs=4',
            link : 'https://kodhia.or.kr/main/',
            thumbImb:'unipics_kodhia',
        },
        {
            company : "unipics",
            filterType : ['A01','A06'],
            title : '제로이드부울경 부산점',
            summary:'고도몰을 사용한 쇼핑몰 홈페이지지이며, 리뉴얼 퍼블리싱을 하였습니다.',
            detail : 'https://www.notion.so/1b8e57ca973b80ea823df70285e8c578?pvs=4',
            link : 'https://zeroidbusan.co.kr/',
            thumbImb:'unipics_zeroid',
        },
        {
            company : "atsome",
            filterType : ['A01'],
            title : '꾸디',
            summary:'php 작업환경에서 적응형 퍼블리싱을 하였습니다.',
            detail : 'https://www.notion.so/ggudi-1ade57ca973b8164a7c6f817285474c4?pvs=4',
            link : 'http://www.ggudi.com/index.php',
            thumbImb:'atsome_ggudi',
        },
        {
            company : "atsome",
            filterType : ['A01','A06'],
            title : '엔투엔퍼니쳐',
            summary:'고도몰을 사용한 쇼핑몰 홈페이지이며, 퍼블리싱 보조로 일을 하면서 html, css 코드 이해를 하였습니다.',
            detail : 'https://www.notion.so/1ade57ca973b81c5a8c1cd0217ab8eb0?pvs=4',
            link : 'https://n2nfurniture.co.kr/',
            thumbImb:'atsome_n2n',
        },
        {
            company : "atsome",
            filterType : ['A01'],
            title : '지지커머스',
            summary:'php 작업환경에서 적응형 퍼블리싱을 하였으며, 보조로 메인 및 서브페이지 작업을 하였으며, 적응형, 앱 화면 퍼블리싱을 작업하였습니다.',
            detail : 'https://www.notion.so/1ade57ca973b817a9bc3f349b5f7454e?pvs=4',
            link : '',
            thumbImb:'atsome_gg',
        },
        {
            company : "atsome",
            filterType : ['A03'],
            title : '유어스쿨',
            summary:'php 작업환경에서 신규 페이지 반응형 퍼블리싱을 하였습니다.',
            detail : 'https://www.notion.so/1ade57ca973b8182bb62fb2a2728eda3?pvs=4',
            link : '',
            thumbImb:'atsome_yourschool',
        },
        {
            company : "atsome",
            filterType : ['A03'],
            title : '대물낚시300일',
            summary:'낚시용품 판매 쇼핑몰 입니다. 하드코딩을 사용하였고, php 환경에서 html, css를 사용하여 작업하였습니다.',
            detail : 'https://www.notion.so/30-1ade57ca973b81a6886ac1df217a901b?pvs=4',
            link : 'http://fishshop.atsomedemo.com/',
            thumbImb:'atsome_fishshop',
        },
        {
            company : "atsome",
            filterType : ['A06','A01'],
            title : '모아푸드',
            summary:'고도몰을 사용한 쇼핑몰 홈페이지이며, 퍼블리싱 메인으로 작업을 하였습니다.',
            detail : 'https://balsam-magnolia-f47.notion.site/1afe57ca973b8053b82fdd9d054f85bd?pvs=74',
            link : '',
            thumbImb:'atsome_moa',
        },
        {
            company : "atsome",
            filterType : ['A06','A01'],
            title : '리바트하움 웹사이트 리뉴얼(고도몰)',
            summary:'고도몰을 사용한 쇼핑몰 홈페이지이며, 퍼블리싱 메인으로 작업을 하였습니다.',
            detail : 'https://balsam-magnolia-f47.notion.site/1afe57ca973b80fab2bdeb85329c35a2',
            link : 'https://haumshowroom.co.kr/',
            thumbImb:'atsome_haum',
        },
        {
            company : "atsome",
            filterType : ['A03'],
            title : '광주에너지파크 웹사이트 리뉴얼',
            summary:'반응형 웹 리뉴얼 및 UI/UX 개선을 진행하여 사용자 경험을 향상 시키는 것을 목표로 했습니다.',
            detail : 'https://balsam-magnolia-f47.notion.site/1afe57ca973b8034bef0c0fed5c64eef',
            link : 'http://jjnet.atsomedemo.com/',
            thumbImb:'atsome_wlwjsspt',
        },
    ],
    companys : [
        {
            cd : 'all',
            title: "전체 포트폴리오",
            period: "2021 - 2025",
            desc: "모든 프로젝트를 확인하실 수 있습니다."
        },
        {
            cd : 'unbiz',
            title: "(주)유엔비즈",
            period: "2023.10 - 2025.03",
            desc: "우리는 최첨단 스포츠 기술을 지향하는 회사로<br>ADMIN 및 KPGA 사이트 A02 위주의 작업을 하였습니다."
        },
        {
            cd : 'unipics',
            title: "(주)유니픽스",
            period: "2022.07 - 2023.08",
            desc: "다양한 금융솔루션 웹앱 및 A03 퍼블리싱을 진행하였습니다."
        },
        {
            cd : 'atsome',
            title: "엣썸",
            period: "2021.09 - 2022.05",
            desc: "패션 브랜드의 이커머스 사이트 운영 및 웹디자인 A02 담당."
        }
    ],
}
