const dataJson = {
    types : [
        {cd : 'A01', nm : '적응형'},
        {cd : 'A02', nm : '유지보수'},
        {cd : 'A03', nm : '반응형'},
        {cd : 'A04', nm : '웹접근성'},
        {cd : 'A05', nm : 'php개발'},

    ],
    works : [
        {
            company : "unbiz",
            filterType : ['A01', 'A02'],
            title : 'KPGA 통합플랫폼 운영 및 고도화 용역',
            summary:'kpga는 한국 남자 프로골프의 공식정보를 확인할수 있는 사이트이며, 사용자 홈페이지 및 Admin 페이지 A02 작업하였습니다.',
            detail : '',
            link : 'https://www.kpga.co.kr/',
            thumbImb:'unbiz_kpga',
        },
        {
            company : "unbiz",
            filterType : ['A02'],
            title : '프로스포츠정보광장',
            summary:'',
            detail : '',
            link : '',
            thumbImb:'unbiz_porsport',
        },
        {
            company : "unbiz",
            filterType : ['A02'],
            title : '대한복싱협회 홈페이지',
            summary:'',
            detail : '',
            link : 'http://boxing.sports.or.kr/',
            thumbImb:'unbiz_boxing',
        },
        {
            company : "unbiz",
            filterType : ['A02'],
            title : '대한펜싱협회 홈페이지',
            summary:'',
            detail : '',
            link : '',
            thumbImb:'unbiz_fencing',
        },
        {
            company : "unbiz",
            filterType : ['A02'],
            title : '대한펜싱협회 앱',
            summary:'',
            detail : '',
            link : '',
            thumbImb:'unbiz_fencingApp',
        },
        {
            company : "unbiz",
            filterType : ['A02'],
            title : '경상남도체육회 홈페이지 A02',
            summary:'',
            detail : '',
            link : 'http://www.gnsports.or.kr/index.do',
            thumbImb:'unbiz_gnsports',
        },
        {
            company : "unbiz",
            filterType : ['A03', 'A04'],
            title : '드웰시티개발',
            summary:'A04 검사를 위해 A02 작업을 하였습니다.',
            detail : '',
            link : 'http://www.thewellcity.kr/',
            thumbImb:'unbiz_thewellcity',
        },
        {
            company : "unbiz",
            filterType : ['A03', 'A04'],
            title : '프로스포츠 암표',
            summary:'웹접근성 검사를 위해 작업을 하였습니다.',
            detail : '',
            link : 'http://report.prosports.or.kr/report',
            thumbImb:'unbiz_porsport_report',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A04'],
            title : '남도사이버갤러리',
            summary:'A04 검사를 위해 A02 작업을 하였습니다.',
            detail : '',
            link : '',
            thumbImb:'unipics_namdo',
        },
        {
            company : "unipics",
            filterType : ['앱'],
            title : '메이커스페이스 앱',
            summary:'',
            detail : '',
            link : '',
            thumbImb:'unipics_makersApp',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A02'],
            title : 'KEA 한국전자정보통신산업진흥회',
            summary:'',
            detail : '',
            link : 'https://www.gokea.org/core/?cid=89',
            thumbImb:'unipics_kea',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A02'],
            title : '한국자동차연구원',
            summary:'',
            detail : '',
            link : 'https://edu.katech.re.kr',
            thumbImb:'unipics_katech',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A02'],
            title : '차세대 바이오헬스산업 혁신인재양성사업',
            summary:'사업안내 페이지에 있는 주관대학 소개 페이지를 A02 작업 하였습니다.',
            detail : '',
            link : 'https://biohealthedu.org/core/?cid=35',
            thumbImb:'unipics_biho',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A02'],
            title : '차세대융합기술연구원 메이커스페이스 전문랩',
            summary:'',
            detail : '',
            link : 'https://www.aictms.or.kr/core/?cid=65',
            thumbImb:'unipics_makers',
        },
        {
            company : "unipics",
            filterType : ['A03', 'A02'],
            title : '미래형자동차 기술혁신인재양성',
            summary:'',
            detail : '',
            link : 'https://www.futurecaredu-bc.org/core/?cid=25',
            thumbImb:'unipics_future',
        },
        {
            company : "unipics",
            filterType : ['A03'],
            title : '한국자동차환경협회 전기차충전인프라 교육센터',
            summary:'',
            detail : '',
            link : 'https://edu.aea.or.kr/main/',
            thumbImb:'unipics_edu',
        },
        {
            company : "unipics",
            filterType : ['A03'],
            title : '미래형자동차 현장인력양성사업',
            summary:'',
            detail : '',
            link : '',
            thumbImb:'unipics_carStudy',
        },
        {
            company : "unipics",
            filterType : ['A03'],
            title : '한국디지털헬스산업협회',
            summary:'',
            detail : '',
            link : 'https://kodhia.or.kr/main/',
            thumbImb:'unipics_kodhia',
        },
        {
            company : "unipics",
            filterType : ['A03'],
            title : '제로이드부울경 부산점',
            summary:'',
            detail : '',
            link : 'https://zeroidbusan.co.kr/',
            thumbImb:'unipics_zeroid',
        },
        {
            company : "atsome",
            filterType : ['A03'],
            title : '꾸디',
            summary:'',
            detail : '',
            link : 'http://www.ggudi.com/index.php',
            thumbImb:'atsome_ggudi',
        },
        {
            company : "atsome",
            filterType : ['A03'],
            title : '엔투엔퍼니쳐',
            summary:'',
            detail : '',
            link : 'https://n2nfurniture.co.kr/',
            thumbImb:'atsome_n2n',
        },
        {
            company : "atsome",
            filterType : ['A03'],
            title : '유어스쿨',
            summary:'',
            detail : '',
            link : '',
            thumbImb:'atsome_yourschool',
        },
        {
            company : "atsome",
            filterType : ['A03'],
            title : '대물낚시300일',
            summary:'',
            detail : '',
            link : 'http://fishshop.atsomedemo.com/',
            thumbImb:'atsome_fishshop',
        },
        {
            company : "atsome",
            filterType : ['A03'],
            title : '모아푸드',
            summary:'',
            detail : '',
            link : '',
            thumbImb:'atsome_moa',
        },
        {
            company : "atsome",
            filterType : ['A03'],
            title : '리바트하움',
            summary:'',
            detail : '',
            link : 'https://haumshowroom.co.kr/',
            thumbImb:'atsome_haum',
        },
        {
            company : "atsome",
            filterType : ['A03'],
            title : '해담마루',
            summary:'',
            detail : '',
            link : 'http://jjnet.atsomedemo.com/',
            thumbImb:'atsome_wlwjsspt',
        },
    ],
    companys : [
        {
            cd : 'all',
            title: "전체 포트폴리오",
            period: "2021 - 2025",
            desc: "모든 프로젝트를 확인하실 수 있습니다."
        },
        {
            cd : 'unbiz',
            title: "(주)유엔비즈",
            period: "2023.10 - 2025.03",
            desc: "우리는 최첨단 스포츠 기술을 지향하는 회사로<br>ADMIN 및 KPGA 사이트 A02 위주의 작업을 하였습니다."
        },
        {
            cd : 'unipics',
            title: "(주)유니픽스",
            period: "2022.07 - 2023.08",
            desc: "다양한 금융솔루션 웹앱 및 A03 퍼블리싱을 진행하였습니다."
        },
        {
            cd : 'atsome',
            title: "엣썸",
            period: "2021.09 - 2022.05",
            desc: "패션 브랜드의 이커머스 사이트 운영 및 웹디자인 A02 담당."
        }
    ],
}
